# Generated by Django 4.2 on 2024-12-15 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Розділ'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Коментар'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-title'], 'verbose_name_plural': 'Зображення'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Допис'},
        ),
    ]
