# Generated by Django 4.2 on 2024-12-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='cat_slug', max_length=30, unique=True),
        ),
    ]
