# Generated by Django 4.2 on 2024-12-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_image_category_image_created_on_image_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
