# Generated by Django 4.2 on 2024-12-24 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0012_alter_post_created_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Розділи'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Коментарі'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Сторінки'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Дописи'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=30, unique=True, verbose_name='Посилання'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(max_length=60, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата створення коментаря'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='blog.post', verbose_name='Допис'),
        ),
        migrations.AlterField(
            model_name='image',
            name='category',
            field=models.ManyToManyField(related_name='category_image', to='blog.category', verbose_name='Розділ'),
        ),
        migrations.AlterField(
            model_name='image',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата створення зображення'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='image',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Посилання'),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='page',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_page', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='page',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата створення сторінки'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Посилання'),
        ),
        migrations.AlterField(
            model_name='page',
            name='status',
            field=models.IntegerField(choices=[(0, 'Чернетка'), (1, 'Опубліковано')], default=0, verbose_name='Стан сторінки'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Назва'),
        ),
    ]
