# Generated by Django 4.2 on 2024-12-24 18:23

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, populate_from='title', unique_with=('created_on__month', 'created_on__year'), verbose_name='Посилання'),
        ),
    ]
