# Generated by Django 4.2 on 2025-01-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.TextField(max_length=300, verbose_name='Повідомлення'),
        ),
    ]
