# Generated by Django 4.2 on 2025-01-14 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0024_alter_category_slug_alter_image_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата створення сторінки'),
        ),
        migrations.CreateModel(
            name='ImageDB',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Назва')),
                ('gd_id', models.CharField(max_length=33)),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата створення допису')),
                ('source', models.TextField(max_length=500, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_by', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name_plural': 'Ілюстрації з GD',
                'ordering': ['-added_on'],
            },
        ),
    ]
